# Generated by Django 6.0.6 on 2026-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('trait', models.CharField(choices=[('O', 'Openness'), ('C', 'Conscientiousness'), ('E', 'Extraversion'), ('A', 'Agreeableness'), ('N', 'Neuroticism')], max_length=1)),
                ('weight', models.IntegerField(default=1)),
                ('reverse_scoring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
