# Generated by Django 6.0.6 on 2026-06-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_userresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openness', models.FloatField(default=0)),
                ('conscientiousness', models.FloatField(default=0)),
                ('extraversion', models.FloatField(default=0)),
                ('agreeableness', models.FloatField(default=0)),
                ('neuroticism', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentsession')),
            ],
        ),
    ]
