# Generated by Django 6.0.6 on 2026-07-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='question',
            name='discrimination',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='facet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
