# Generated by Django 6.0.6 on 2026-07-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_question_difficulty_question_discrimination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_roman',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
