# Generated by Django 6.0.6 on 2026-06-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_traits', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
