# Generated by Django 6.0.6 on 2026-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Medical', 'Medical'), ('Education', 'Education'), ('Business', 'Business'), ('Engineering', 'Engineering'), ('Creative', 'Creative'), ('Public Service', 'Public Service')], default='Technology', max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='max_neuroticism',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='career',
            name='min_agreeableness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='career',
            name='min_conscientiousness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='career',
            name='min_extraversion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='career',
            name='min_openness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='career',
            name='required_traits',
            field=models.CharField(max_length=200),
        ),
    ]
