# Generated by Django 6.0.6 on 2026-07-10 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_question_question_text_roman_and_more'),
        ('recommendations', '0002_career_category_career_max_neuroticism_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('is_relevant', models.BooleanField(default=True, help_text='User considers this career suitable.')),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_feedbacks', to='assessment.assessmentresult')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'assessment_result', 'career'), name='unique_user_result_career_feedback')],
            },
        ),
    ]
