# Generated by Django 6.0.6 on 2026-07-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_careerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('current_accuracy', models.FloatField(default=0)),
                ('previous_accuracy', models.FloatField(default=0)),
                ('feedback_since_last_training', models.PositiveIntegerField(default=0)),
                ('last_retrained', models.DateTimeField(blank=True, null=True)),
                ('retraining_running', models.BooleanField(default=False)),
            ],
        ),
    ]
