# Generated by Django 6.0.6 on 2026-07-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_aimodelstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfeedback',
            name='used_for_training',
            field=models.BooleanField(default=False, help_text='Shows whether this feedback has already been used for model retraining.'),
        ),
    ]
