# Generated by Django 6.1 on 2026-08-18 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_question_question_text_roman_and_more'),
        ('recommendations', '0007_usercareergoal_userdailylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=5)),
                ('current_question_index', models.PositiveIntegerField(default=1)),
                ('overall_score', models.FloatField(default=0.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('star_score', models.FloatField(default=0.0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('summary_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='assessment.assessmentresult')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='recommendations.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('stage', models.CharField(choices=[('HR', 'HR & Behavioral'), ('TECHNICAL', 'Technical & Concepts'), ('SITUATIONAL', 'Situational Scenario')], default='HR', max_length=20)),
                ('question_text', models.TextField()),
                ('user_answer', models.TextField(blank=True)),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('structure_score', models.FloatField(default=0.0)),
                ('overall_question_score', models.FloatField(default=0.0)),
                ('feedback_notes', models.TextField(blank=True)),
                ('ideal_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='recommendations.userinterviewsession')),
            ],
            options={
                'ordering': ['question_number'],
                'constraints': [models.UniqueConstraint(fields=('session', 'question_number'), name='unique_session_question_number')],
            },
        ),
    ]
